### ISSUE TITLE
how to correctly install cupy

### ISSUE THREAD

**Issue by twangnh** [conda-forge/cupy-feedstock#133]
Hi, recently we are trying to install the cupy, I first create a new conda environment, then run 
`conda install -c conda-forge cupy`, after that trying to import cupy, but got the following error
```
>>> import cupy
Traceback (most recent call last):
  File "/home/wangtao/anaconda3_2/envs/sann/lib/python3.6/site-packages/cupy/__init__.py", line 16, in <module>
    from cupy import _core  # NOQA
  File "/home/wangtao/anaconda3_2/envs/sann/lib/python3.6/site-packages/cupy/_core/__init__.py", line 1, in <module>
    from cupy._core import core  # NOQA
  File "cupy/_core/core.pyx", line 1, in init cupy._core.core
  File "/home/wangtao/anaconda3_2/envs/sann/lib/python3.6/site-packages/cupy/cuda/__init__.py", line 8, in <module>
    from cupy.cuda import compiler  # NOQA
  File "/home/wangtao/anaconda3_2/envs/sann/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 12, in <module>
    from cupy.cuda import function
  File "cupy/cuda/function.pyx", line 1, in init cupy.cuda.function
  File "cupy/cuda/texture.pyx", line 1, in init cupy.cuda.texture
ImportError: /home/wangtao/anaconda3_2/envs/sann/lib/python3.6/site-packages/cupy_backends/cuda/api/driver.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cuDevicePrimaryCtxRelease_v2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wangtao/anaconda3_2/envs/sann/lib/python3.6/site-packages/cupy/__init__.py", line 37, in <module>
    raise ImportError(_msg) from e
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

original error: /home/wangtao/anaconda3_2/envs/sann/lib/python3.6/site-packages/cupy_backends/cuda/api/driver.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cuDevicePrimaryCtxRelease_v2
```

when using `CUDA_PATH=/usr/local/cuda-10.1 pip install cupy`, I got the following error

```
Collecting cupy
  Using cached cupy-9.1.0.tar.gz (1.6 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/wangtao/anaconda3_2/envs/sann/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xdx909pk/cupy_a59ddd0d5d874522be0bc947969f8b6f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xdx909pk/cupy_a59ddd0d5d874522be0bc947969f8b6f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-bgbfnf50
         cwd: /tmp/pip-install-xdx909pk/cupy_a59ddd0d5d874522be0bc947969f8b6f/
    Complete output (14 lines):
    Options: {'package_name': 'cupy', 'long_description': None, 'wheel_libs': [], 'wheel_includes': [], 'wheel_metadata': None, 'no_rpath': False, 'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False, 'use_hip': False}
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xdx909pk/cupy_a59ddd0d5d874522be0bc947969f8b6f/setup.py", line 117, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "/tmp/pip-install-xdx909pk/cupy_a59ddd0d5d874522be0bc947969f8b6f/cupy_setup_build.py", line 924, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "/tmp/pip-install-xdx909pk/cupy_a59ddd0d5d874522be0bc947969f8b6f/cupy_setup_build.py", line 617, in make_extensions
        settings = build.get_compiler_setting(use_hip)
      File "/tmp/pip-install-xdx909pk/cupy_a59ddd0d5d874522be0bc947969f8b6f/install/build.py", line 147, in get_compiler_setting
        cuda_path = get_cuda_path()
      File "/tmp/pip-install-xdx909pk/cupy_a59ddd0d5d874522be0bc947969f8b6f/install/build.py", line 73, in get_cuda_path
        nvcc_path = utils.search_on_path(('nvcc', 'nvcc.exe'))
    AttributeError: module 'utils' has no attribute 'search_on_path'
```

**Comment by leofang** [comment]
@twangnh Could you provide the outputs of `conda list` and `conda info`?

**Comment by leofang** [comment]
@twangnh Closing as no response. Feel free to reopen if this is still an issue for you.
