### ISSUE TITLE
Low disk space warnings/errors on Azure

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cupy-feedstock#290]
From comment ( https://github.com/conda-forge/cupy-feedstock/pull/289#issuecomment-2406443758 ):

> [One of the Windows builds]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1051584&view=logs&j=ea6b747a-d678-5a49-8233-1092783ec463&t=f2d2e250-6953-5cdb-0f87-35009083fa88&s=6884a131-87da-5381-61f3-d7acc3b91d76 ) ran out of disk space while creating the host environment
> 
> There were a few warnings that led up to it
> 
> ```
> ##[warning]Free disk space on D:\ is lower than 5%; Currently used: 99.69%
> ##[warning]Free disk space on D:\ is lower than 5%; Currently used: 99.69%
> ##[warning]Free disk space on D:\ is lower than 5%; Currently used: 99.69%
> ##[warning]Free disk space on D:\ is lower than 5%; Currently used: 99.69%
> ##[warning]Free disk space on D:\ is lower than 5%; Currently used: 99.69%
> ```
> 
> Here is the actual error:
> 
> ```python
> ERROR conda.core.link:_execute(950): An error occurred while installing package 'conda-forge::python-3.11.10-hce54a09_2_cpython'.
> Executing transaction: ...working... done
> Rolling back transaction: ...working... done
> Traceback (most recent call last):
>   File "C:\Miniforge\Scripts\conda-build-script.py", line 10, in <module>
>     sys.exit(execute())
>              ^^^^^^^^^
>   File "C:\Miniforge\Lib\site-packages\conda_build\cli\main_build.py", line 589, in execute
>     api.build(
>   File "C:\Miniforge\Lib\site-packages\conda_build\api.py", line 209, in build
>     return build_tree(
>            ^^^^^^^^^^^
>   File "C:\Miniforge\Lib\site-packages\conda_build\build.py", line 3655, in build_tree
>     packages_from_this = build(
>                          ^^^^^^
>   File "C:\Miniforge\Lib\site-packages\conda_build\build.py", line 2701, in build
>     environ.create_env(
>   File "C:\Miniforge\Lib\site-packages\conda_build\environ.py", line 1050, in create_env
>     _execute_actions(prefix, precs)
>   File "C:\Miniforge\Lib\site-packages\conda_build\environ.py", line 1340, in _execute_actions
>     unlink_link_transaction.execute()
>   File "C:\Miniforge\Lib\site-packages\conda\core\link.py", line 354, in execute
>     self._execute(
>   File "C:\Miniforge\Lib\site-packages\conda\core\link.py", line 970, in _execute
>     raise CondaMultiError(
> conda.CondaMultiError: [Errno 28] No space left on device
> ()
> ```
> 
> Similar warnings are showing up for all of the CI builds (Windows & Linux)
> 
> Went ahead and restarted so we can fix the issue this PR was created for. We can follow up on this other item in a new issue
> 
> _Originally posted by @jakirkham in https://github.com/conda-forge/cupy-feedstock/issues/289#issuecomment-2406443758_
>

**Comment by jakirkham** [comment]
Think this got better after this conda-smithy change: https://github.com/conda-forge/conda-smithy/pull/2076

Haven't seen this as much sense

The main issue now is memory usage, which is tracked in issue: https://github.com/conda-forge/cupy-feedstock/issues/301

Will close this out. Can always reopen if needed
